embed_static: on
package_assets: off
compress_assets: off
# asset_root: ../


javascripts:
  asset_bundles:
    - &app_core
      # Vendor
      - static/js/math_polyfill.js
      - static/js/numeral.min.js

      - static/js/time_formatters.js
      - static/js/data_formatters.js
      - static/js/prototype.js
      - static/js/event.simulate.js

      - static/js/leaflet.ksp.js

      - static/js/settings.js
      - static/js/telemachus.js

      - static/js/title_bar.js
      - static/js/button_indicator.js
      - static/js/readout_table.js
      - static/js/resource_monitor.js
      - static/js/data_table.js

      # Components to move into own category?
      - static/js/atmospheric_density_gauge.js
      - static/js/throttle_gauge.js

    - &3d_map
      - static/js/three.min.js
      - static/js/THREEx.FullScreen.js
      - static/js/orbit_controls.js
      - static/js/tween.min.js
      - static/js/dat.gui.min.js

      - static/js/orbital_position_data.js
      - static/js/position_data_formatter.js
      - static/js/orbital_map.js
      - static/js/resizeSensor.js

    - &navball
      - static/js/three.min.js
      - static/js/tween.min.js
      - static/js/navball.js

    - &position_map
      - static/js/L.Graticule.js
      - static/js/position_map.js

    - &altitude_tracker
      - static/js/chartist.min.js
      - static/js/altitude_tracker.js

    - &docking_map
      - static/js/three.min.js
      - static/js/THREEx.FullScreen.js
      - static/js/orbit_controls.js
      - static/js/tween.min.js
      - static/js/dat.gui.min.js

      - static/js/docking_position_data.js
      - static/js/docking_map.js
      - static/js/resizeSensor.js

    - &hohmann_intercept
      - static/js/hohmann-intercept.js

    - &current_stage_burn_info
      - static/js/orbital_math.js
      - static/js/current_stage_burn_info.js

    - &burn_planner
      - static/js/orbital_math.js
      - static/js/burn_planner.js

    - &staging_info_table
      - static/js/orbital_math.js
      - static/js/staging_info_table.js

    - &ground_track
      - static/js/chartist.min.js
      - static/js/L.Graticule.js
      - static/js/position_map.js

      - static/js/orbital_position_data.js
      - static/js/ground_track_position_data_formatter.js
      - static/js/ground_track.js
      - static/js/ground_track_container.js

    - &navigation_orbit_info_table
      - static/js/navigation_orbit_info_table.js

    - &orbiting_body_info_table
      - static/js/orbiting_body_info_table.js

    - &maneuver_node_editor
      - static/js/maneuver_node_editor.js

    - &camera_feed
      - static/js/camera_feed.js

  3dmap:
    - *app_core
    - *3d_map

  ascension:
    - *app_core
    - *position_map
    - *navball
    - *altitude_tracker
    - *camera_feed

  boost:
    - *app_core
    - *navball
    - *current_stage_burn_info
    - *burn_planner
    - *staging_info_table

  camera:
    - *app_core
    - *camera_feed

  docking:
    - *app_core
    - *navball
    - *docking_map
    - *camera_feed

  ground-track:
    - *app_core
    - *ground_track

  landing:
    - *app_core
    - *ground_track
    - *navball
    - *altitude_tracker
    - *camera_feed

  mission-wall:
    - *app_core
    - *ground_track
    - *3d_map
    - *camera_feed

  navigation:
    - *app_core
    - *3d_map
    - *hohmann_intercept
    - *navigation_orbit_info_table
    - *maneuver_node_editor

  staging-analysis:
    - *app_core
    - *current_stage_burn_info
    - *staging_info_table

  sysops:
    - *app_core
    - *position_map
    - *orbiting_body_info_table

  vessel-overview:
    - *app_core
    - *ground_track
    - *camera_feed

  app:
    - *app_core

stylesheets:
  app:
    - static/stylesheets/chartist.min.css
    - static/stylesheets/leafletksp.css
    - static/stylesheets/camera.css
    - static/stylesheets/application.css
  3dmap:
    - static/stylesheets/3dmap.css
  ascension:
    - static/stylesheets/ascension.css
  boost:
    - static/stylesheets/boost.css
  fido:
    - static/stylesheets/fido.css
  ground-track:
    - static/stylesheets/ground-track.css
  landing:
    - static/stylesheets/landing.css
  science:
    - static/stylesheets/science.css